Error at track_progress

Traceback (most recent call last):
  File "c:\Users\liamr\Desktop\Projects\MapMaker\main.py", line 155, in track_progress
    time.sleep(0.1)
KeyboardInterrupt

Input "section_progress": <SynchronizedArray wrapper for <multiprocessing.sharedctypes.c_long_Array_4 object at 0x00000245E787F550>>
Input "section_progress_total": <SynchronizedArray wrapper for <multiprocessing.sharedctypes.c_long_Array_4 object at 0x00000245E787FD50>>
Input "start_time": 1736023172.3882701


Error at assign_sections

Traceback (most recent call last):
  File "c:\Users\liamr\Desktop\Projects\MapMaker\main.py", line 243, in assign_sections
    dots[index] = Dot(ref_dot.x, ref_dot.y, "Land")
    ~~~~^^^^^^^
  File "<string>", line 2, in __setitem__
  File "C:\Users\liamr\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\managers.py", line 821, in _callmethod
    kind, result = conn.recv()
                   ^^^^^^^^^^^
  File "C:\Users\liamr\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\connection.py", line 250, in recv
    buf = self._recv_bytes()
          ^^^^^^^^^^^^^^^^^^
  File "C:\Users\liamr\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\connection.py", line 321, in _recv_bytes
    waitres = _winapi.WaitForMultipleObjects(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt

Input "island_size": 20
Input "origin_dots": (Not available, length: 686)
Input "local_dots": (Not available)


Error at assign_sections

Traceback (most recent call last):
  File "c:\Users\liamr\Desktop\Projects\MapMaker\main.py", line 243, in assign_sections
    dots[index] = Dot(ref_dot.x, ref_dot.y, "Land")
    ~~~~^^^^^^^
  File "<string>", line 2, in __setitem__
  File "C:\Users\liamr\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\managers.py", line 820, in _callmethod
    conn.send((self._id, methodname, args, kwds))
  File "C:\Users\liamr\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "C:\Users\liamr\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\connection.py", line 289, in _send_bytes
    ov, err = _winapi.WriteFile(self._handle, buf, overlapped=True)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt

Input "island_size": 20
Input "origin_dots": (Not available, length: 686)
Input "local_dots": (Not available)


Error at assign_sections

Traceback (most recent call last):
  File "c:\Users\liamr\Desktop\Projects\MapMaker\main.py", line 231, in assign_sections
    tree = scipy.spatial.KDTree([(dot.x, dot.y) for dot in local_dots])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\liamr\AppData\Local\Programs\Python\Python312\Lib\site-packages\scipy\spatial\_kdtree.py", line 355, in __init__
    data = np.asarray(data)
           ^^^^^^^^^^^^^^^^
KeyboardInterrupt

Input "island_size": 20
Input "origin_dots": (Not available, length: 686)
Input "local_dots": (Not available)


Error at assign_sections

Traceback (most recent call last):
  File "c:\Users\liamr\Desktop\Projects\MapMaker\main.py", line 243, in assign_sections
    dots[index] = Dot(ref_dot.x, ref_dot.y, "Land")
    ~~~~^^^^^^^
  File "<string>", line 2, in __setitem__
  File "C:\Users\liamr\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\managers.py", line 821, in _callmethod
    kind, result = conn.recv()
                   ^^^^^^^^^^^
  File "C:\Users\liamr\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\connection.py", line 250, in recv
    buf = self._recv_bytes()
          ^^^^^^^^^^^^^^^^^^
  File "C:\Users\liamr\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\connection.py", line 317, in _recv_bytes
    ov, err = _winapi.ReadFile(self._handle, bsize,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt

Input "island_size": 20
Input "origin_dots": (Not available, length: 686)
Input "local_dots": (Not available)


Error at Pool Parent Process

Traceback (most recent call last):
  File "c:\Users\liamr\Desktop\Projects\MapMaker\main.py", line 429, in main
    [result.wait() for result in results]
     ^^^^^^^^^^^^^
  File "C:\Users\liamr\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\pool.py", line 765, in wait
    self._event.wait(timeout)
  File "C:\Users\liamr\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 655, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\liamr\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 355, in wait
    waiter.acquire()
KeyboardInterrupt



